trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
        version: 3.0.100-preview4-010737
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration)'

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
        version: 3.0.100-preview4-010737
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration)'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
        version: 3.0.100-preview4-010737
  - task: DotNetCoreCLI@2
    inputs:
      command: test
      arguments: '--configuration $(buildConfiguration)'